#!/usr/bin/with-contenv bash
# shellcheck shell=bash

exec \
  /usr/local/bin/readsb \
  --net \
  --net-only \
  --quiet \
  --net-heartbeat 60 \
  --net-ro-size 1280 \
  --net-beast-reduce-interval "${REDUCE_INTERVAL}" \
  --net-connector feed.adsbexchange.com,30005,beast_reduce_out \
  --net-connector "${BEASTHOST}","${BEASTPORT}",beast_in \
  --net-ro-interval 0.2 \
  --net-ri-port 0 \
  --net-ro-port 0 \
  --net-sbs-port 0 \
  --net-bi-port 0 \
  --net-bo-port 0 \
  --stats-every="${LOG_INTERVAL}" \
  --write-json="${ADSBX_JSON_PATH}" \
  2>&1 | awk -W interactive '{print "[adsbexchange-feed] " $0}'
