#!/command/with-contenv bash
# shellcheck shell=bash

mkdir -p "${ADSBX_JSON_PATH}"
exec \
  /usr/local/bin/readsb \
  --net \
  --net-only \
  --quiet \
  --uuid-file=/boot/adsbx-uuid \
  --net-beast-reduce-interval "${REDUCE_INTERVAL}" \
  --net-connector "${ADSB_FEED_DESTINATION_HOSTNAME},${ADSB_FEED_DESTINATION_PORT},${ADSB_FEED_DESTINATION_TYPE},${ADSB_FEED_SECONDARY_DESTINATION_HOSTNAME},${ADSB_FEED_SECONDARY_DESTINATION_PORT}" \
  --net-connector "${BEASTHOST}","${BEASTPORT}",beast_in \
  --net-ro-interval 0.2 \
  --net-ri-port 0 \
  --net-ro-port 0 \
  --net-sbs-port 0 \
  --net-bi-port 0 \
  --net-bo-port 30005 \
  --stats-every="${LOG_INTERVAL}" \
  --write-json="${ADSBX_JSON_PATH}" \
  2>&1 | stdbuf -o0 sed --unbuffered '/^$/d' | mawk -W interactive '{print "[adsbexchange-feed] " $0}'

  # stdbuf -o0 sed --unbuffered '/^$/d'  --  (remove blank lines from output)
  # awk -W interactive '{print "[adsbexchange-feed] " $0}'  --  (prefix log messages with "[adsbexchange-feed]")
