#!/usr/bin/with-contenv bash
# shellcheck shell=bash


MLAT_CMD="mlat-client"
MLAT_PARAM=(--input-type "${MLAT_INPUT_TYPE}")
MLAT_PARAM+=(--no-udp)
MLAT_PARAM+=(--input-connect "${BEASTHOST}:${BEASTPORT}")
MLAT_PARAM+=(--server "${MLAT_FEED_DESTINATION_HOSTNAME}:${MLAT_FEED_DESTINATION_PORT}")
MLAT_PARAM+=(--user "${SITENAME}")
MLAT_PARAM+=(--lat "${LAT}")
MLAT_PARAM+=(--lon "${LONG}")
MLAT_PARAM+=(--alt "${ALT}")
MLAT_PARAM+=(--results "beast,listen,30105")
if [[ ${PRIVATE_MLAT} == true ]]; then
    MLAT_PARAM+=(--privacy)
fi

set -eo pipefail
exec \
    "${MLAT_CMD}" "${MLAT_PARAM[@]}" 2>&1 | mawk -W interactive '{print "[mlat-client] " $0}'
