#!/command/with-contenv bash
# shellcheck shell=bash

mkdir -p "${ADSBX_STATS_PATH}"
# greps suppress jq errors that happen on container startup or for new users

if [[ -n "${STATS_DISABLE}" ]]; then
    while sleep 86400; do
        true
    done
    exit 0
fi

# shellcheck disable=SC2016
exec \
    /usr/local/bin/json-status 2>&1 \
    | stdbuf -o0 grep -vE 'jq: error .* \(null\) number required' \
    | stdbuf -o0 grep -vE 'jq: error .* \(null\) and number \(0\) cannot be divided' \
    | stdbuf -o0 mawk -W interactive '{print "[adsbexchange-stats] " $0}'
