#!/usr/bin/with-contenv bash
# shellcheck shell=bash

s6-setuidgid adsbx sleep 900
s6-setuidgid adsbx \
    /scripts/health_from_adsbexchange.py \
    | awk -W interactive '{print "[healthcheck] " $0}'
