#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# greps suppress jq errors that happen on container startup or for new users

# shellcheck disable=SC2016
exec \
    /usr/local/bin/json-status 2>&1 \
    | stdbuf -o0 grep -vE 'jq: error .* \(null\) number required' \
    | stdbuf -o0 grep -vE 'jq: error .* \(null\) and number \(0\) cannot be divided' \
    | stdbuf -o0 awk -W interactive '{print "[adsbexchange-stats] " $0}'
