#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Define bash colours
NOCOLOR='\033[0m'
LIGHTRED='\033[1;31m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'

# Check to make sure the correct command line arguments have been set
EXITCODE=0
if [ -z "${LAT}" ]; then
  echo -e "${LIGHTRED}ERROR: LAT environment variable not set${NOCOLOR}"
  EXITCODE=1
fi
if [ -z "${LONG}" ]; then
  echo -e "${LIGHTRED}ERROR: LONG environment variable not set${NOCOLOR}"
  EXITCODE=1
fi
if [ -z "${BEASTHOST}" ]; then
  echo -e "${LIGHTRED}ERROR: BEASTHOST environment variable not set${NOCOLOR}"
  EXITCODE=1
fi
if [ -z "${ALT}" ]; then
  echo -e "${LIGHTRED}ERROR: ALT environment variable not set${NOCOLOR}"
  EXITCODE=1
fi
if [ -z "${SITENAME}" ]; then
  echo -e "${LIGHTRED}ERROR: SITENAME environment variable not set${NOCOLOR}"
  EXITCODE=1
fi
if [ -z "${UUID}" ]; then
  echo -e "${LIGHTRED}ERROR: UUID environment variable was not set${NOCOLOR}"
  EXITCODE=1
fi

# Check to make sure ALT includes "m" or "ft" suffix if positive
if ! echo "${ALT}" | grep -P '(^\-{0}[\d\.]+(m{0,1}|ft)$|^-[\d\.]+$)' > /dev/null 2>&1; then
  echo -e "${LIGHTRED}ERROR: ALT should be either:"
  echo -e "  * A positive number ending in 'm' (for metres) or 'ft' (for feet)'; or"
  echo -e "  * A positive number with no suffix (for metres)"
  echo -e "  * A negative number in metres (no suffix) for below sea level.${NOCOLOR}"
  EXITCODE=1
fi

# If any errors above are fatal, don't proceed starting the container
if [ $EXITCODE -ne 0 ]; then
  exit 1
fi

# Set up timezone
if [ -z "${TZ}" ]; then
  echo -e "${YELLOW}WARNING: TZ environment variable not set${NOCOLOR}"
else
  ln -snf "/usr/share/zoneinfo/$TZ" /tmp/localtime && echo "$TZ" > /etc/timezone
fi

# Sanitize site name
SITENAME="$(echo -e "${SITENAME}" | tr -dc '[a-zA-Z0-9]_\-')"

# Write UUID file
echo "$UUID" > /boot/adsbx-uuid
echo -e "${CYAN}Statistics available at: https://www.adsbexchange.com/api/feeders/?feed=${UUID}${NOCOLOR}"
